<div class="page-title">
    <h1><?php echo $this->__('Oink Guest Checkout'); ?></h1>
</div>
<ol class="opc">
    <form method="POST" action="<?php echo $this->getFormActionUrl() ?>" id="oinkParentConfirm" >
        <?php echo $this->getChildHtml("CSelect") ?>
        <?php echo $this->getChildHtml("payment") ?>
        
        <div class="buttons-set" id="billing-buttons-container">
            <button type="submit" title="<?php echo $this->__('Continue'); ?>" class="button" ><span><span><?php echo $this->__('Continue') ?></span></span></button>
        </div>
    </form>
</ol>
<script type="text/javascript" >
//<![CDATA[
    var oinkParentConfirm = new VarienForm('oinkParentConfirm', true);
//]]>
</script>