<?php
/* @var $this Oink_Oink_Block_Checkout_ParentConfirm_CSelect */
$childrens = $this->getChildrens();
?>



<li class="section allow active" id="opc-billing">
    <div class="step-title">
        <h2><?php echo $this->__("Child information") ?></h2>
    </div>

    <div id="checkout-step-billing" class="step a-item" style="">
        <fieldset>
            <dl class="sp-methods">
                <dd id="billing-new-address-form">
                    <fieldset>
                        <ul>
                            <li class="fields">
                                <div class="field">
                                    <label for="children" class="required">This transaction is for</label>
                                    <div class="input-box">
                                        <select name="children" id="cSelect" class="required-entry">
                                            <option value="" ></option>
                                            <?php foreach ($childrens as $key => $children): ?>
                                                <option value="<?php echo $children->getChildrenIdentifier() ?>"><?php echo $children->getName() ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                </dd>
                <dd class="control">
                    <ul>
                        <li>
                            <input type="checkbox" id="deliverToChildAddress" name="deliverToChildAddress" value="1" />
                            <label for="deliverToChildAddress" ><?php echo $this->__("Deliver to this child's address") ?></label>
                        </li>
                    </ul>
                </dd>
            </dl>
        </fieldset>
    </div>
</li>