<style>
    #oink-checkout {
        border-radius: 4px !important;
        background:white !important;
    }


    #oink-cart-button {
        display: inline-block !important;
        margin-top: <?php echo Mage::getStoreConfig("oink/checkoutbutton/oink_cart_checkout_margin_top").'px;'; ?>
    }

    .oink-h2
    {
        padding-bottom: 5px !important;
        font-size: 19px !important;
        display: block !important;
        text-align: center !important;
        font-family: Helvetica,'Open Sans Condensed',sans-serif !important;
        font-weight: 200 !important;
        color: #444444 !important;
        line-height: 20px !important;
    }


    #oink-checkout-button {
        float: left !important;
    }

    .overlay_magento {
        background-color: #000 !important;
        filter:alpha(opacity=60) !important;
        -moz-opacity: 0.6 !important;
        opacity: 0.6 !important;
    }

    div#info-panel {
        color: #999999 !important;
        display:inline-block !important;
        text-align: center !important;
        margin-left: auto !important;
        margin-right: auto !important;
        width:180px !important;
        height:300px !important;
        padding: 3px 10px 0px 15px !important;
        vertical-align:top !important;
        background-color: #F3F3F3 !important;
        border-radius: 4px !important;
    }

    .dim
    {
        filter:alpha(opacity=50); /* IE */
        opacity: 0.5; /* Safari, Opera */
        -moz-opacity:0.50; /* FireFox */
    }

    #oink-login #vp-close {
        background: url('<?php echo $skinUrl; ?>x.png') no-repeat;
        cursor: pointer !important;
        height: 17px !important;
        position: absolute !important;
        right: 30px !important;
        top: 30px !important;
        width: 17px !important;
    }

    #login-form-button {
        border: 1px solid #EE7A27 !important;
        background-color: #F57D28 !important;
        background: -moz-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #f68b3e), color-stop(100%, #ee7a27));
        background: -webkit-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -o-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: -ms-linear-gradient(top, #f68b3e 0%, #ee7a27 100%);
        background: linear-gradient(to bottom, #f68b3e 0%, #ee7a27 100%);
    }
    #sign-up-button {
        width: 130px !important;
        height: 26px !important;
        line-height:26px !important;
        border: 1px solid #03A2A7;
        background-color: #0AA5A8;
        margin-left:415px !important;
        margin-top:-47px !important;
        background: -moz-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #39c4cb), color-stop(100%, #03a2a7));
        background: -webkit-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -o-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: -ms-linear-gradient(top, #39c4cb 0%, #03a2a7 100%);
        background: linear-gradient(to bottom, #39c4cb 0%, #03a2a7 100%);
    }
    .oink-button {
        color: #ffffff !important;
        cursor: pointer !important;
        text-decoration: none !important;
        height: 28px !important;
        font-size: 14px !important;
        min-width: 88px !important;
        border-radius: 4px !important;
        text-align: center !important;
        margin-left: auto !important;
        margin-right: auto !important;
        display:inline-block;
        vertical-align: middle !important;
    }

    .oink-note {
        color: #666666 !important;
        font-size: 11px !important;
        text-decoration: none !important;
        font-family: Helvetica,'Open Sans Condensed',sans-serif !important;
        font-weight: 200 !important;
    }

    #oink-login {
        float: left !important;
        display: inline-block !important;
        width: 350px !important;
        position: relative !important;
        background-color: white;
        box-shadow: 3px 0px 5px -2px rgba(0, 0, 0, 0.25);
        padding: 0px 20px 0px 20px !important;
        height:303px !important;
        border-top-left-radius:4px !important;
        border-bottom-left-radius:4px !important;
    }
    #oink-login-userid, #oink-login-password
    {
        border: 1px solid #c0c0bf !important;
        border-radius: 4px !important;
        color: #666 !important;
        font-size: 10pt !important;
        padding: 5px !important;
        width: 345px !important;
        text-decoration: none !important;
        font-family: Helvetica,'Open Sans Condensed',sans-serif !important;
    }

    div#oink-modal {
        background-color: #F3F3F3 !important;
        box-shadow: 0 10px 10px rgba(0,0,0,0.3);
        border-radius: 4px !important;
        height: 300px !important;
        z-index: 100000000 !important; /*Some merchants have weird z-index values that force our modal underneath elements*/
    }
    .oink-block{
        border-radius: 4px !important;
        background-color: #F3F3F3 !important;
    }
    #oink-close {
        float:right;
        padding-top:10px;
        position: relative;
        left:10px;
    }
    .spinner {
        text-align: center !important;
        display:none;
        border-radius:4px !important;
        margin:0 !important;
        width: 350px !important;
    }

    .spinner img {
        width: 54px !important;
        height: 54px !important;
        margin-top: 55px !important;
        margin-bottom: 10px !important;

        -webkit-transition-property: -webkit-transform;
        -webkit-transition-duration: 1s;
        -moz-transition-property: -moz-transform;
        -moz-transition-duration: 1s;
        -webkit-animation-name: spinner-rotate;
        -webkit-animation-duration: 1s;
        -webkit-animation-iteration-count: infinite;
        -webkit-animation-timing-function: linear;
        -moz-animation-name: spinner-rotate;
        -moz-animation-duration: 1s;
        -moz-animation-iteration-count: infinite;
        -moz-animation-timing-function: linear;
    }

    @-webkit-keyframes spinner-rotate {
        from {-webkit-transform: rotate(0deg);}
        to {-webkit-transform: rotate(360deg);}
    }

    @-moz-keyframes spinner-rotate {
        from {-moz-transform: rotate(0deg);}
        to {-moz-transform: rotate(360deg);}
    }

    .spinner h3 {
        margin-bottom: 5px;

        font-size: 1.3em;
    }

    .spinner p {
        margin: 0;
    }

    ::-webkit-input-placeholder {
        color: #c0c0bf !important;
    }

    :-moz-placeholder { /* Firefox 18- */
        color: #c0c0bf !important;
    }

    ::-moz-placeholder {  /* Firefox 19+ */
        color: #c0c0bf !important;
    }

    :-ms-input-placeholder {
        color: #c0c0bf !important;
    }
</style>

<?php $skinUrl = $this->getSkinUrl('images/oink/checkout/'); ?>
<?php $baseJsUrl = Mage::getBaseUrl('js'); ?>

<link rel="stylesheet" type="text/css" href="<?php echo $baseJsUrl ?>prototype/windows/themes/default.css"/>
<link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:bold&v1' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="<?php echo $baseJsUrl ?>prototype/window.js"></script>

<div id="oink-modal" align="center" style="display:none;">
    <div align="left" class="oink-block">
        <!-- left col -->
        <div id="oink-login" align="center">
            <div id="oink-close"><a style="text-decoration:none;cursor:pointer;" onClick="return closePopup()"><img src="<?php echo $skinUrl; ?>x.png" /></a></div>
            <img src="//cdn.virtualpiggy.com/public/images/checkout-logo-192x75.png" style="width:18em; padding-top:20px; padding-bottom:20px;"/>
            <form id="oink-checkout">
                <div align="center" style="padding-top:10px;">
                    <input class="textBox required-entry" onkeypress="bindOinkLoginPost(event)" onfocus="stopAutoCenter()" onblur="autoCenter()" id="oink-login-userid" name="UserName" tabindex="2" type="text" placeholder="Username" />
                </div>
                <div align="center" style="padding-top:5px;">
                    <input autocomplete="off" onkeypress="bindOinkLoginPost(event)" onfocus="stopAutoCenter()" onblur="autoCenter()" class="textBox required-entry" id="oink-login-password" name="Password" tabindex="3" type="password" placeholder="Password" />
                    <div class="opensans" style="font-size:10pt;color:#ff0000;" id="oink-errors-container">&nbsp;</div>
                    <div><a href="//users.virtualpiggy.com/login/resetpassword" target="_blank" class="oink-note" style="margin-top: 10px">Forgot Password?</a></div>
                    <button onclick="return oinkLoginForm.submit();" id="login-form-button" class="oink-button" type="button">Login</button>
                </div>
            </form>

            <a href="//users.virtualpiggy.com/registration" target="_blank" id="sign-up-button" class="oink-button">Sign Up</a>
            <div id="oink-loading" class="spinner page">
                <img src="<?php echo $skinUrl; ?>spinner.png" alt="" />
            </div>
        </div>
    </div>
    <div align="right" id="info-panel-wrapper" style="margin:0px; background-color:#F3F3F3; border-radius:4px;">
        <div id="info-panel" align="center">
            <div style="padding-top:50px;">
                <span class="oink-h2">What is Oink?</span>
            </div>
            <div style="padding-top:15px;">
                <span style="font-size:10pt;color:#444;">Oink is the safe way for kids and teens to save, shop and give online.</span>
            </div>
            <div style="padding-top:10px">
                <a href="//www.oink.com/" target="_blank" class="oink-note">Learn More</a>
            </div>
        </div>
    </div>
</div>


<input type="hidden" id="oink-checkout-url" value="<?php echo $this->getCheckoutUrl() ?>"/>
<script type="text/javascript">
    //<![CDATA[


    function showSpinner() {
        $('oink-login').setStyle({backgroundColor: '#BBBBBB'});
        $('oink-loading').setStyle({ display: 'block'});
        $('oink-checkout').setStyle({ display: 'none'});
        $('sign-up-button').setStyle({ display: 'none'});
        return false;
    }

    function hideSpinner() {
        $('oink-loading').setStyle({ display: 'none'});
        $('oink-checkout').setStyle({ display: 'block'});
        $('oink-login').setStyle({backgroundColor: 'white'});
        $('sign-up-button').setStyle({ display: 'inline-block'});
    }

    function closePopup(){
        if($('p_method_oink'))$('p_method_oink').checked=false;
        Dialog.cancelCallback();
        return false;
    }

    function bindOinkLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            oinkLoginForm.submit();
        }
    }

    if ("payment" in window)
    {
        var oldSwitchMethod=payment.switchMethod;
        payment.switchMethod=function(method){
            if(method=="oink"){
                oinkLoginForm.toggleTooltip()
            }else{
                oldSwitchMethod.apply(this,[method])
            }
        }
    }

    var oinkLoginForm = new VarienForm('oink-modal', true);

    oinkLoginForm.toggleTooltip=function(){
        if($$(".dialog").length){
            return false;
        }
        if($('p_method_oink')){
            $('p_method_oink').checked=1;
        }
        if ( isMobile() ) {
            $('info-panel-wrapper').setStyle({ display: 'none'});
            $('sign-up-button').setStyle({ display: 'none'});
            $('oink-login').setStyle({ borderRadius: '4px', boxShadow: 'none'});
            Dialog.info($('oink-modal').innerHTML, {
                className:"magento",
                width: 370,
                height:300,
                zIndex:100000,
                top: ((screen.height - 320)/2 ),
                left: ((window.innerWidth- 370)/2),
                recenterAuto:false
            });
        } else {
            Dialog.info($('oink-modal').innerHTML, {
                id: "oink-modal-float",
                className:"magento",
                width:600,
                height:300,
                zIndex:100000,
                hideEffect:Element.hide,
                showEffect:Element.show,
                top: ((window.innerHeight - 300)/2),
                left: ((window.innerWidth - 600)/2),
                recenterAuto:true
            });
            $('oink-close').setStyle({ left: '220px'});
        }
        return false;
    }
    function stopAutoCenter() {
    }
    function autoCenter() {
    }
    function isMobile() {
        if(screen.width < 768) {
            return true;
        }
        return false;
    }
    oinkLoginForm.submit=function(){
        var user=$('oink-login-userid').value;
        var password=$('oink-login-password').value;

        if(this.validator && this.validator.validate()){
            new Ajax.Request("<?php echo $this->getLoginPostUrl() ?>",{
                method:"post",
                parameters:{
                    "user" : user,
                    "password" : password
                },

                onCreate:function() {
                    $('info-panel').addClassName('dim');
                    showSpinner();
                },

                onComplete:function(transport) {
                    var json=eval('(' + transport.responseText + ')');

                    if(json.response) {
                        setLocation($("oink-checkout-url").value);
                        $('oink-errors-container').innerHTML = '';
                    }
                    else {
                        hideSpinner();
                        $('oink-errors-container').innerHTML = json.errorMessage;
                        $('info-panel').removeClassName('dim');

                        if (! isMobile() ) {
                            $('oink-close').setStyle({ left: '220px'});
                        }

                        $('login-form-button').innerHTML = '<button onclick="return oinkLoginForm.submit();" id="login-form-button" class="oink-button" type="button">Login</button>';
                    }
                }
            });
        }

        return false;
    }
    //]]>
</script>